--- libump-9999/Makefile.orig	2013-01-25 19:46:13.000000000 +0000
+++ libump-9999/Makefile	2013-01-25 19:45:14.000000000 +0000
@@ -37,14 +37,15 @@
 	$(TARGET_AR) rcs $@ $(UMP_OBJS)
 
 install: all
-	$(INSTALL) libUMP.so $(libdir)/libUMP.so
-	mkdir $(includedir)/ump
-	$(INSTALL) include/ump/ump.h $(includedir)/ump/ump.h
-	$(INSTALL) include/ump/ump_platform.h  $(includedir)/ump/ump_platform.h	
-	$(INSTALL) include/ump/ump_debug.h  $(includedir)/ump/ump_debug.h
-	$(INSTALL) include/ump/ump_osu.h  $(includedir)/ump/ump_osu.h
-	$(INSTALL) include/ump/ump_ref_drv.h  $(includedir)/ump/ump_ref_drv.h
-	$(INSTALL) include/ump/ump_uk_types.h  $(includedir)/ump/ump_uk_types.h
+	mkdir $(DESTDIR)$(libdir) -p
+	$(INSTALL) libUMP.so $(DESTDIR)$(libdir)/libUMP.so
+	mkdir $(DESTDIR)$(includedir)/ump -p
+	$(INSTALL) include/ump/ump.h $(DESTDIR)$(includedir)/ump/ump.h
+	$(INSTALL) include/ump/ump_platform.h $(DESTDIR)$(includedir)/ump/ump_platform.h	
+	$(INSTALL) include/ump/ump_debug.h $(DESTDIR)$(includedir)/ump/ump_debug.h
+	$(INSTALL) include/ump/ump_osu.h $(DESTDIR)$(includedir)/ump/ump_osu.h
+	$(INSTALL) include/ump/ump_ref_drv.h $(DESTDIR)$(includedir)/ump/ump_ref_drv.h
+	$(INSTALL) include/ump/ump_uk_types.h $(DESTDIR)$(includedir)/ump/ump_uk_types.h
 
 .DEFAULT_GOAL = all
 all: libUMP.so libUMP.a
