--- aaa/Makefile.config	2013-03-14 17:29:59.000000000 +0000
+++ bbb/Makefile.config	2013-03-14 16:47:37.000000000 +0000
@@ -22,6 +22,8 @@
     ABI = armhf
   else ifeq ($(dumpmachine),armv7hl-redhat-linux-gnueabi) # fedora HF
     ABI = armhf
+  else ifeq ($(dumpmachine),armv7a-hardfloat-linux-gnueabi) # gentoo HF
+    ABI = armhf
   endif
   $(info ABI="$(ABI)" (Detected))
 else
--- aaa/Makefile.setup	2013-03-14 22:15:17.999326771 +0400
+++ bbb/Makefile.setup	2013-03-14 22:14:55.849338364 +0400
@@ -1,4 +1,4 @@
-prefix ?= /usr/
+prefix ?= $(DESTDIR)/
 libdir ?= $(prefix)lib/
 includedir ?= $(prefix)/include

