#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

: ${GITPREP_DIR:=/var/lib/gitprep}
: ${GITPREP_SCRIPT:=${GITPREP_DIR}/script/gitprep}

export PERL5LIB

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --user gitprep --group git --exec /usr/bin/hypnotoad \
		-- "${GITPREP_SCRIPT}"
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --user gitprep --group git --exec /usr/bin/hypnotoad \
		-- "${GITPREP_SCRIPT}" --stop
	eend $?
}
